platform :ios, '7.0'
pod 'hpple',             '~> 0.2.0'
pod 'UIImage+Additions', '~> 1.0.1'
pod 'UIImageEffects',    '~> 0.0.1'
pod 'iOS-blur',          '~> 0.0.5'
pod 'BlocksKit',         '~> 2.2.2'
pod 'CRToast',           '~> 0.0.7'
pod 'Reveal-iOS-SDK',    '~> 1.0.4'
pod 'NSLogger',          '~> 1.2'